[package]
name = "xml-parser-combinators"
version = "0.1.0"
authors = ["Philipp Lühmann <spam@philipp.lu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
